# Generated by Django 4.2.3 on 2023-12-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_payment_received_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="amount",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="material",
            name="unit",
            field=models.CharField(
                choices=[("KILOGRAM", "kilogram"), ("GRAM", "gram")],
                default="gram",
                max_length=20,
            ),
        ),
    ]
