# Generated by Django 4.2.3 on 2023-12-10 08:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_order_amount_alter_material_unit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="materials",
        ),
    ]
