# Generated by Django 4.2.1 on 2023-12-10 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0004_remove_appointment_materials"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="employee",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="actual_quantity",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "active"),
                    ("ACCEPTED", "accepted"),
                    ("COMPLETED", "COMPLETED"),
                    ("REJECTED", "rejected"),
                ],
                default="active",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="unit",
            field=models.CharField(
                choices=[
                    ("KILOGRAM", "kilogram"),
                    ("GRAM", "gram"),
                    ("POUND", "pound"),
                    ("OUNCE", "ounce"),
                ],
                default="gram",
                max_length=20,
            ),
        ),
    ]
