# Generated by Django 4.2.1 on 2023-12-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_appointment_employee_order_actual_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="actual_quantity",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="order",
            name="quantity",
            field=models.FloatField(),
        ),
    ]
