# Generated by Django 4.2.3 on 2023-12-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_order_actual_quantity_alter_order_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='actual_quantity',
            new_name='assessed_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='assessed_quantity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('ACCEPTED', 'accepted'), ('COMPLETED', 'completed'), ('REJECTED', 'rejected')], default='active', max_length=10),
        ),
    ]
