# Generated by Django 4.2.3 on 2023-11-19 17:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_managers_user_user_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="personaldetails",
            name="addres1",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="personaldetails",
            name="addres2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="personaldetails",
            name="cnic",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="personaldetails",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="personaldetails",
            name="mobile_number",
            field=models.CharField(default=django.utils.timezone.now, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="personaldetails",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="personaldetails",
            name="vehicle_no",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="personaldetails",
            name="vehicle_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TWO_WHEELER", "two wheeler"),
                    ("THREE_WHEELER", "three wheeler"),
                    ("FOUR_WHEELER", "four wheeler"),
                ],
                default="two wheeler",
                max_length=13,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="personaldetails",
            name="phone_number",
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("CUSTOMER", "customer"), ("EMPLOYEE", "employee")],
                default="customer",
                max_length=10,
            ),
        ),
    ]
